name: Sync to GitHub-Sync-Master

on:
  push:
    branches: [ main ]

jobs:
  Sync-Up:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SYNC_MASTER_REPO_TOKEN }}
          fetch-depth: 0
      - run: |
          git remote add github-sync-master https://github.com/Richard-Barrett/github-sync-master
          git push --set-upstream github-sync-master main